name: pages build and deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Build and export
        run: |
          npm run build
          npm run export
      - name: Disable Jekyll for Pages
        run: |
          echo "" > out/.nojekyll

      - name: Debug: list exported files
        run: |
          echo "--- out directory tree ---"
          ls -la out || true
          echo "--- recurse out/_next ---"
          ls -la out/_next || true
          echo "--- css files ---"
          ls -la out/_next/static/css || true
          echo "--- head of index.html ---"
          head -n 40 out/index.html || true

      - name: Deploy to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          cd out
          # configure git
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(pages): deploy static export from workflow" || true
          # force push to gh-pages
          git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${{ github.repository }}" HEAD:gh-pages
